# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c214945dd5ec507ab3336c85d9cbbd7c37eca8bff8f3a1e90c3a80418ca37d9a9ec07d2cc1c776fbec735825562ea513e8fe0d915788fff528e8ddc0bb249cfa

test:
  secret_key_base: b01bd246a09a5119ef12c8ff4776cfbb5aeda4f59f1097c9c8d680d5ab8dd48e065b73e4dd40d3d4546e3c4fbf8a58801edbd50128eb5258eef18bc1ce8d2569

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
